---
title: "Duodenum Histology"
author: "Chloe J McGovern"
date: "`r Sys.Date()`"
output:
  html_document:
    css: "styles.css"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "/Figures/03_DuodenumHistology")
```

# Duodenum Histology

## Why do you look at the duodenum under the microscope? 



## Staining: What do we use and what do we see? 


# Objective:

# Load in data and any other necessities

```{r set-up}
pacman::p_load(tidyverse, patchwork, install = FALSE)

#load times new roman font
windowsFonts("Times New Roman" = windowsFont("Times New Roman"))

theme(
    text = element_text(family = "Times New Roman")
)

lphy_histo <- read.csv("Data/CSVs/mix-histology-duod.csv")

glimpse(mix_histo)
```


# Analysis

## 1. Villis Height

## 2. Villis Width

## 3. Villus Surface Area

## 4. Crypt Depth

## 5. CD:VS Ratio Graph

## 6. Making a publication ready figure